### ISSUE TITLE
Check output path

### ISSUE THREAD

**Issue by bordoray** [MIERUNE/ElevationTile4JP#32]
Error thrown when output path has not .tiff format

```
2024-06-11T16:04:43     WARNING    Traceback (most recent call last):
              File "/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ElevationTile4JP/get_tiles.py", line 125, in calc
              elevation_tile.calc()
              File "/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ElevationTile4JP/elevation_tile_tools/elevation_tile_converter.py", line 138, in calc
              geotiff.write_geotiff(
              File "/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ElevationTile4JP/elevation_tile_tools/geotiff.py", line 39, in write_geotiff
              dst_ds.SetGeoTransform(geotransform)
             AttributeError: 'NoneType' object has no attribute 'SetGeoTransform'
```

**Comment by bordoray** [comment]
- Works when it is not tiff format /Users/.../something
  - create tiff without extension → to add
- Does not work when folder path does not exists → to debug
